services:
  gallery:
    image: greyhats_gallery:latest
    ports:
      - "34267:3000"
    environment:
      FLAG: "${FLAG:-grey{fake_flag}}"
    mem_limit: 128m
    cpus: 0.2
    init: true
    cap_drop:
      - NET_RAW
    restart: "no"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
